# Mod Loading Info
modLoader="javafml"
loaderVersion="${loader_version_range}"

# Instrumental Config
license="${mod_license}"

[[mods]]
modId="instrumental"
version="${mod_version}"
displayName="${mod_name}"
logoFile="villagecraft2essentials.png"
credits="${mod_credits}"
authors="${mod_authors}"
description='''${mod_description}'''

# Dependency for Forge
[[dependencies.instrumental]] 
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

# Dependency for Minecraft
[[dependencies.instrumental]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"